INSERT INTO  MEASUREMENT_UNIT(measurement_unit_name) VALUES 
('INCH'),
('CENTIMETER'),
('METER'),
('KILOMETER'),
('FEET'),
('KILOGRAM'),
('GRAM'),
('MILIGRAM'),
('LITRE'),
('MILILITRE');

INSERT INTO  COLOR(COLOR_NAME) VALUES 
('RED'),
('GREEN'),
('BLUE'),
('YELLOW'),
('ORANGE'),
('WHITE'),
('BLACK'),
('MAGENTA'),
('PINK'),
('BROWN');

INSERT INTO  SUPPLIER(GST_ID, SUPPLIER_NAME) VALUES 
('SUPPLIER_GST_1','RAM'),
('SUPPLIER_GST_2','RAHIM'),
('SUPPLIER_GST_3','KARAN'),
('SUPPLIER_GST_4','ARJUN'),
('SUPPLIER_GST_5','SITA'),
('SUPPLIER_GST_6','GEETA'),
('SUPPLIER_GST_7','RITA'),
('SUPPLIER_GST_8','NITA'),
('SUPPLIER_GST_9','BABITA'),
('SUPPLIER_GST_10','SUNNY');

INSERT INTO  SELLER(GST_ID, SELLER_NAME) VALUES 
('SELLER_GST_1','RAMS'),
('SELLER_GST_2','RAHIMS'),
('SELLER_GST_3','KARANS'),
('SELLER_GST_4','ARJUNS'),
('SELLER_GST_5','SITAS'),
('SELLER_GST_6','GEETAS'),
('SELLER_GST_7','RITAS'),
('SELLER_GST_8','NITAS'),
('SELLER_GST_9','BABITAS'),
('SELLER_GST_10','SUNNYS');

INSERT INTO PRODUCT (PRODUCT_NAME, COLOR_ID, SIZE, MEASUREMENT_UNIT_ID) VALUES
  ('SHIRT', 1, 36,1),
  ('SHIRT', 2, 46,1),
  ('SHIRT', 3, 56,1),
  ('TV', 2, 15,1),
  ('TV', 3, 40,1),
  ('TABLE', 5, 50,3),
  ('PEN', 1, 3,1);
  
INSERT INTO PRODUCT_SUPPLIER (PRODUCT_ID, SUPPLIER_ID) VALUES
  (1,1),
  (1,2),
  (2,1),
  (3,1),
  (3,2),
  (3,3),
  (4,1),
  (4,2),
  (4,3),
  (4,4),
  (5,3),
  (5,7),
  (6,1);
  
INSERT INTO PRODUCT_SELLER (PRODUCT_ID, SELLER_ID) VALUES
  (1,1),
  (2,1),
  (3,1),
  (4,3),
  (4,4),
  (5,3),
  (5,7),
  (6,1),
  (6,2),
  (6,3),
  (6,5);
  
 