create table MEASUREMENT_UNIT
(
	MEASUREMENT_UNIT_ID IDENTITY NOT NULL PRIMARY KEY, 
	MEASUREMENT_UNIT_NAME varchar(50)
);

create table COLOR
(
	COLOR_ID IDENTITY NOT NULL PRIMARY KEY, 
	COLOR_NAME varchar(50)
);

create table SUPPLIER
(
	SUPPLIER_ID IDENTITY NOT NULL PRIMARY KEY, 
	GST_ID varchar(50),
	SUPPLIER_NAME varchar(50)
);


create table SELLER
(
	SELLER_ID IDENTITY NOT NULL PRIMARY KEY, 
	GST_ID varchar(50),
	SELLER_NAME varchar(100)
);

create table PRODUCT 
(
	 PRODUCT_ID IDENTITY NOT NULL PRIMARY KEY,       
     PRODUCT_NAME varchar(255),  
     COLOR_ID number,         
     SIZE number,
     MEASUREMENT_UNIT_ID number,
     CONSTRAINT FK_MEASUREMENT_UNIT_ID FOREIGN KEY (MEASUREMENT_UNIT_ID) REFERENCES MEASUREMENT_UNIT(MEASUREMENT_UNIT_ID),
     CONSTRAINT FK_COLOR_ID FOREIGN KEY (COLOR_ID) REFERENCES COLOR(COLOR_ID)
);

create table PRODUCT_SUPPLIER
(
	PRODUCT_SUPPLIER_ID IDENTITY NOT NULL PRIMARY KEY, 
	PRODUCT_ID number, 
	SUPPLIER_ID number,
	CONSTRAINT FK_PRODUCT_SUPPLIER_PR_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
	CONSTRAINT FK_PRODUCT_SUPPLIER_SU_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID)
);

create table PRODUCT_SELLER
(
	PRODUCT_SELLER_ID IDENTITY NOT NULL PRIMARY KEY, 
	PRODUCT_ID number, 
	SELLER_ID number, 
	CONSTRAINT FK_PRODUCT_SELLER_PR_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
	CONSTRAINT FK_PRODUCT_SELLER_SE_ID FOREIGN KEY (SELLER_ID) REFERENCES SELLER(SELLER_ID)
);


